"""v2.2.0 schema update

Revision ID: 001_v2_2_0
Revises:
Create Date: 2026-03-11

Manual migration — diff between prod v2.1.2 and current models.
NOT autogenerated (local DB may differ from prod).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "001_v2_2_0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # =========================================================================
    # transcription_jobs
    # =========================================================================

    # Drop old guest_uid index and column (IF EXISTS — index may not exist on all envs)
    op.execute("DROP INDEX IF EXISTS ix_transcription_jobs_guest_uid")
    op.drop_column("transcription_jobs", "guest_uid")

    # Add new columns
    op.add_column("transcription_jobs", sa.Column("is_private", sa.Boolean(), nullable=False, server_default="false"))
    op.add_column("transcription_jobs", sa.Column("flash_input_tokens", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("transcription_jobs", sa.Column("flash_output_tokens", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("transcription_jobs", sa.Column("pro_input_tokens", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("transcription_jobs", sa.Column("pro_output_tokens", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("transcription_jobs", sa.Column("report_json", sa.JSON(), nullable=True))

    # Add composite indexes
    op.create_index("idx_job_user_status_created", "transcription_jobs", ["user_id", "status", "created_at"])
    op.create_index("idx_job_status_created", "transcription_jobs", ["status", "created_at"])

    # Safety: fix invalid status values before adding CHECK constraint
    op.execute(
        "UPDATE transcription_jobs SET status = 'failed' "
        "WHERE status NOT IN ('pending','queued','processing','completed','failed','expired')"
    )
    op.create_check_constraint(
        "ck_job_status",
        "transcription_jobs",
        "status IN ('pending','queued','processing','completed','failed','expired')",
    )

    # =========================================================================
    # construction_reports
    # =========================================================================

    # Drop old guest_uid index and column (IF EXISTS — index may not exist on all envs)
    op.execute("DROP INDEX IF EXISTS ix_construction_reports_guest_uid")
    op.drop_column("construction_reports", "guest_uid")

    # Add new column
    op.add_column("construction_reports", sa.Column("summary_path", sa.String(1000), nullable=True))

    # =========================================================================
    # user_domain_assignments
    # =========================================================================

    # Safety: remove duplicates before adding unique constraint
    op.execute(
        "DELETE FROM user_domain_assignments "
        "WHERE id NOT IN ("
        "  SELECT MIN(id) FROM user_domain_assignments GROUP BY user_id, domain"
        ")"
    )
    op.create_unique_constraint("uq_user_domain", "user_domain_assignments", ["user_id", "domain"])

    # =========================================================================
    # user_project_access_records
    # =========================================================================

    # Safety: remove duplicates before adding unique constraint
    op.execute(
        "DELETE FROM user_project_access_records "
        "WHERE id NOT IN ("
        "  SELECT MIN(id) FROM user_project_access_records GROUP BY user_id, project_id"
        ")"
    )
    op.create_unique_constraint("uq_user_project", "user_project_access_records", ["user_id", "project_id"])


def downgrade() -> None:
    # =========================================================================
    # user_project_access_records
    # =========================================================================
    op.drop_constraint("uq_user_project", "user_project_access_records", type_="unique")

    # =========================================================================
    # user_domain_assignments
    # =========================================================================
    op.drop_constraint("uq_user_domain", "user_domain_assignments", type_="unique")

    # =========================================================================
    # construction_reports
    # =========================================================================
    op.drop_column("construction_reports", "summary_path")
    op.add_column("construction_reports", sa.Column("guest_uid", sa.String(100), nullable=True))
    op.create_index("ix_construction_reports_guest_uid", "construction_reports", ["guest_uid"])

    # =========================================================================
    # transcription_jobs
    # =========================================================================
    op.drop_constraint("ck_job_status", "transcription_jobs", type_="check")
    op.drop_index("idx_job_status_created", table_name="transcription_jobs")
    op.drop_index("idx_job_user_status_created", table_name="transcription_jobs")

    op.drop_column("transcription_jobs", "report_json")
    op.drop_column("transcription_jobs", "pro_output_tokens")
    op.drop_column("transcription_jobs", "pro_input_tokens")
    op.drop_column("transcription_jobs", "flash_output_tokens")
    op.drop_column("transcription_jobs", "flash_input_tokens")
    op.drop_column("transcription_jobs", "is_private")

    op.add_column("transcription_jobs", sa.Column("guest_uid", sa.String(100), nullable=True))
    op.create_index("ix_transcription_jobs_guest_uid", "transcription_jobs", ["guest_uid"])
